site_name: Cronus Eater
repo_url: https://github.com/breno-jesus-fernandes/cronus-eater
repo_name: breno-jesus-fernandes/cronus-eater
edit_uri: tree/main/docs

theme:
  name: material
  language: en
  logo: assets/cronus-eater-logo.png
  favicon: assets/cronus-eater-logo.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber

extra_css:
  - stylesheets/extra.css

watch:
  - cronus_eater

plugins:
  - exclude:
      glob:
        - setup/*

  - macros
  - mkdocstrings:
      handlers:
        python:
          paths: [cronus_eater]

extra:
  commands:
    run: cronus-eater
