site_name: Cronus Eater
repo_url: https://github.com/breno-jesus-fernandes/cronus-eater
repo_name: breno-jesus-fernandes/cronus-eater
edit_uri: tree/main/docs

theme:
  name: material
  language: en
  logo: assets/cronus-eater-logo.png
  favicon: assets/cronus-eater-logo.png
  palette:
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber

extra_css:
  - stylesheets/extra.css

watch:
   - cronus_eater
