name: "Pipeline"

on:
  push:
    paths:
      - "**.py"
      - "**.pyi"
      - "pyproject.toml"
      - ".github/**.yaml"
  pull_request:
    paths:
      - "**.py"
      - "**.pyi"
      - "pyproject.toml"
      - ".github/**.yaml"
  workflow_dispatch:

jobs:
  released:
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ matrix.os }}-${{ matrix.python-version }}
      cancel-in-progress: true
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Install project dependencies
        uses: ./.github/setup
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

      - name: Check Blue Style
        run: poetry run blue --check cronus_eater tests

      - name: Check Isort Style
        run: poetry run isort --check cronus_eater tests

      - name: Run pytest
        run: poetry run pytest
      
      - name: Run coverage test
        run: poetry run pytest -s -x --cov=cronus_eater tests -vv --cov-report=xml
      
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

