name: 'Test'

on:
  push:
    paths:
      - '**.py'
      - '**.pyi'
      - 'pyproject.toml'
      - '.github/workflows/test.yml'
  pull_request:
  workflow_dispatch:


jobs:
  released:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Install project dependencies
      uses: ./.github/setup
      with:
        os: ${{ matrix.os }}
        python-version: ${{ matrix.python-version }}

    - name: Run pytest
      run: poetry run pytest
